name: PolyHxApp
description: Official PolyHx Mobile App

dependencies:
  shared_preferences: ^0.4.2
  intl:
  redux: ^3.0.0
  flutter_redux:
  font_awesome_flutter: ^8.0.1
  qr_reader: ^0.1.3
  cupertino_icons: ^0.1.0
  flutter:
    sdk: flutter
  rxdart: ^0.18.1
  redux_epics: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/tshirt.png
