name: CSGamesApp
description: Official CSGames Mobile App

dependencies:
  shared_preferences: ^0.4.2
  intl:
  redux: ^3.0.0
  flutter_redux:
  font_awesome_flutter: ^8.0.1
  qr_reader: ^0.1.3
  cupertino_icons: ^0.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.18.1
  redux_epics: ^0.10.0
  flutter_spinkit: ^2.1.0
  qr_flutter: ^2.0.0+51
  url_launcher: ^3.0.0
  http: ^0.12.0
  crypto: ^2.0.6
  firebase_messaging: ^2.1.0
  google_maps_flutter: ^0.3.0+2
  timeago: ^2.0.10
  flutter_local_notifications: ^0.4.3
  photo_view: ^0.2.1
  flutter_html: ^0.9.4
  flutter_markdown: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/tshirt.png
    - assets/mirego.png
    - assets/bnc.png
    - assets/cfp.png
    - assets/cse.png

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: Flipbash
      fonts:
        - asset: fonts/Flipbash.otf
