kind: Deployment
apiVersion: apps/v1
metadata:
  name: csgames-mail-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csgames-mail-prod
  template:
    metadata:
      labels:
        app: csgames-mail-prod
        keel.sh/policy: force
    spec:
      imagePullSecrets:
        - name: githubcred
      containers:
      - name: csgames-mail-prod
        image: "docker.pkg.github.com/csgames/event-platform/mail-service:latest"
        resources:
          requests:
            cpu: "60m"
          limits:
            cpu: "70m"
        env:
        # Base config
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: PORT
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: VERSION

        # Database config
        - name: DB_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: DB_ADDRESS
        - name: DB_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: DB_ADDRESS
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: DB_PASSWORD

        # Mailgun config
        - name: MAILGUN_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: MAILGUN_DOMAIN
        - name: MAILGUN_API_KEY
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: MAILGUN_API_KEY

        # JWT and CORS Config
        - name: JWKS_URI
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: JWKS_URI
        - name: JWT_AUDIENCES
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: JWT_AUDIENCES
        - name: JWT_ISSUER
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: JWT_ISSUER
        - name: ALLOW_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: mail-configmap-prod
              key: ALLOW_ORIGINS