kind: Deployment
apiVersion: apps/v1
metadata:
  name: csgames-gateway-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csgames-gateway-staging
  template:
    metadata:
      labels:
        app: csgames-gateway-staging
        keel.sh/policy: force
    spec:
      volumes:
      - name: sts-key
        secret:
          secretName: public-key
      - name: proxy-config
        secret:
          secretName: proxy-config-staging
      containers:
      - name: csgames-gateway-staging
        image: "polyhx/csgames-gateway:latest"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "100m"
        volumeMounts:
        - name: sts-key
          mountPath: /var/secret
        - name: proxy-config
          mountPath: /var/config
        env:
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: APP_URL
        - name: COOKIE_SECRET
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: COOKIE_SECRET
        - name: GATEWAY_BASE_PATH
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: GATEWAY_BASE_PATH
        - name: IS_HTTPS
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: IS_HTTPS
        - name: PROXY_CONFIG_PATH
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: PROXY_CONFIG_PATH
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: PORT
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: REDIS_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: REDIS_PASSWORD
        - name: STS_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: STS_CLIENT_ID
        - name: STS_CLIENT_SCOPES
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: STS_CLIENT_SCOPES
        - name: STS_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: STS_CLIENT_SECRET
        - name: STS_URL
          valueFrom:
            configMapKeyRef:
              name: gateway-configmap-staging
              key: STS_URL