kind: Deployment
apiVersion: apps/v1
metadata:
  name: csgames-sts-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csgames-sts-staging
  template:
    metadata:
      labels:
        app: csgames-sts-staging
        keel.sh/policy: force
    spec:
      volumes:
      - name: certificates
        persistentVolumeClaim:
          claimName: sts-staging-certificates
      imagePullSecrets:
        - name: githubcred
      containers:
      - name: csgames-sts-staging
        image: "docker.pkg.github.com/csgames/event-platform/auth-service:latest"
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "250m"
        volumeMounts:
        - name: certificates
          mountPath: /var/keys
        env:
        # Base config
        - name: ASPNETCORE_ENVIRONMENT
          value: Staging
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: PORT

        # Database config
        - name: DB_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: DB_CONNECTION_STRING
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: DB_NAME

        # Identity server config
        - name: ALLOW_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: ALLOW_ORIGINS
        - name: AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: AUDIENCE
        - name: CERTIFICATES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: CERTIFICATES_PASSWORD
        - name: CERTIFICATES_PATH
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: CERTIFICATES_PATH
        - name: ISSUER_URI
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: ISSUER_URI
        - name: ISSUERS
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: ISSUERS

        # Email url config
        - name: CONFIRM_EMAIL_URL
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: CONFIRM_EMAIL_URL
        - name: RESET_PASSWORD_URL
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: RESET_PASSWORD_URL

        # STS client config
        - name: STS_API_URL
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: STS_API_URL
        - name: STS_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: STS_CLIENT_ID
        - name: STS_CLIENT_SCOPE
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: STS_CLIENT_SCOPE
        - name: STS_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: STS_CLIENT_SECRET

        # Mail client config
        - name: MAIL_API_URL
          valueFrom:
            configMapKeyRef:
              name: sts-configmap-staging
              key: MAIL_API_URL
        - name: DEPLOYMENT_VALUE
          value: a
